version: '2'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: x
      MYSQL_DATABASE: test
  mysql2:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: x
      MYSQL_DATABASE: test
  mysql-sync:
    image: 'klsmith/mysql-sync:latest'
    environment:
      - SRC_HOST=mysql
      - SRC_NAME=test
      - SRC_PASS=x
      - SRC_USER=root
      - DEST_HOST=mysql2
      - DEST_NAME=test
      - DEST_PASS=x
      - DEST_USER=root